<?php

declare(strict_types=1);

namespace PhpAiToolkit\DocGen\Render;

use function sprintf;

/**
 * Renders the shared document shell around every generated page.
 */
final class PageChrome
{
    /**
     * Renders one complete HTML document.
     */
    public function page(RenderKit $services, string $pagePath, string $title, string $breadcrumbHtml, string $sidebarHtml, string $contentHtml): string
    {
        $escaper = $services->escaper;
        $prefix = $services->url->prefix($pagePath);

        return '<!DOCTYPE html>' . "\n"
            . '<html lang="en">' . "\n"
            . '<head>' . "\n"
            . '<meta charset="utf-8">' . "\n"
            . '<meta name="viewport" content="width=device-width, initial-scale=1">' . "\n"
            . sprintf('<title>%s — %s</title>', $escaper->e($title), $escaper->e($services->model->title)) . "\n"
            . sprintf('<link rel="stylesheet" href="%sassets/style.css">', $escaper->e($prefix)) . "\n"
            . '<script>try{var t=localStorage.getItem("docgen-theme");if(t){document.documentElement.dataset.theme=t}}catch(e){}</script>' . "\n"
            . '</head>' . "\n"
            . sprintf('<body data-root="%s">', $escaper->e($prefix)) . "\n"
            . '<nav class="sidebar" id="sidebar">' . $sidebarHtml . '</nav>' . "\n"
            . '<div class="page">' . "\n"
            . '<header class="topbar">' . "\n"
            . '<button class="nav-toggle" id="nav-toggle" title="Toggle navigation">☰</button>' . "\n"
            . '<nav class="crumbs">' . $breadcrumbHtml . '</nav>' . "\n"
            . '<div class="topbar-tools">' . "\n"
            . '<input type="search" id="search" placeholder="Search… ( / )" autocomplete="off" spellcheck="false">' . "\n"
            . '<button id="theme-toggle" title="Toggle theme">◐</button>' . "\n"
            . '</div>' . "\n"
            . '</header>' . "\n"
            . '<div class="search-results" id="search-results" hidden></div>' . "\n"
            . '<main class="content">' . "\n" . $contentHtml . '</main>' . "\n"
            . '<footer class="site-footer">Generated by <a href="https://github.com/k-kinzal/php-ai-toolkit">php-ai-toolkit</a> doc-gen</footer>' . "\n"
            . '</div>' . "\n"
            . sprintf('<script src="%sassets/search-index.js" defer></script>', $escaper->e($prefix)) . "\n"
            . sprintf('<script src="%sassets/app.js" defer></script>', $escaper->e($prefix)) . "\n"
            . '</body>' . "\n"
            . '</html>' . "\n";
    }
}
