<?php

declare(strict_types=1);

namespace Toolkit\DocGen\Render;

use function sprintf;

use Toolkit\DocGen\Render\Diff\DiffModeControl;
use Toolkit\DocGen\Render\Social\SocialMeta;

/**
 * Renders the shared document shell around every generated page.
 */
final class PageChrome
{
    /**
     * Display mode a diff site starts in before a reader chooses one.
     */
    public const DEFAULT_DIFF_MODE = 'inline';

    /** @readonly */
    private DiffModeControl $diffModes;

    /** @readonly */
    private SocialMeta $social;

    /** @readonly */
    private RepositoryLink $repository;

    /**
     * Creates the page shell renderer from its topbar collaborators.
     */
    public function __construct(?DiffModeControl $diffModes = null, ?SocialMeta $social = null, ?RepositoryLink $repository = null)
    {
        $this->diffModes = $diffModes ?? new DiffModeControl();
        $this->social = $social ?? new SocialMeta();
        $this->repository = $repository ?? new RepositoryLink();
    }

    /**
     * Renders one complete HTML document.
     *
     * @param string $description what this page documents, in one sentence, for the preview a link to it is shown with
     */
    public function page(RenderKit $services, string $pagePath, string $title, string $description, string $breadcrumbHtml, string $sidebarHtml, string $contentHtml): string
    {
        $escaper = $services->escaper;
        $prefix = $services->url->prefix($pagePath);

        return '<!DOCTYPE html>' . "\n"
            . '<html lang="en">' . "\n"
            . '<head>' . "\n"
            . '<meta charset="utf-8">' . "\n"
            . '<meta name="viewport" content="width=device-width, initial-scale=1">' . "\n"
            . sprintf('<title>%s — %s</title>', $escaper->e($title), $escaper->e($services->model->title)) . "\n"
            . $this->social->render($services, $pagePath, $title, $description)
            . sprintf('<link rel="stylesheet" href="%sassets/document-design-v1.0.0.css">', $escaper->e($prefix)) . "\n"
            . sprintf('<link rel="stylesheet" href="%sassets/style.css">', $escaper->e($prefix)) . "\n"
            . $this->bootstrap($services) . "\n"
            . '</head>' . "\n"
            . sprintf('<body data-root="%s">', $escaper->e($prefix)) . "\n"
            . '<a class="skip" href="#content">Skip to content</a><div class="doc">' . "\n"
            . '<aside class="sidebar" id="sidebar" aria-label="Documentation navigation">' . $sidebarHtml . '</aside>' . "\n"
            . '<div class="main">' . "\n"
            . '<header class="topbar">' . "\n"
            . '<button class="btn nav-toggle" id="nav-toggle" type="button" aria-controls="sidebar" aria-expanded="false" title="Toggle navigation">☰</button>' . "\n"
            . '<nav class="breadcrumbs" aria-label="Breadcrumb">' . $breadcrumbHtml . '</nav>' . "\n"
            . '<div class="topbar-tools">' . "\n"
            . '<input class="input input-search" type="search" id="search" aria-label="Search documentation" placeholder="Search… ( / )" autocomplete="off" spellcheck="false">' . "\n"
            . $this->diffModes->render($services)
            . $this->repository->topbar($services)
            . '<button class="btn" type="button" id="theme-toggle" title="Toggle theme">◐</button>' . "\n"
            . '</div>' . "\n"
            . '</header>' . "\n"
            . '<div class="search-results" id="search-results" hidden></div>' . "\n"
            . '<main class="content" id="content">' . "\n" . $this->emptyHint($services) . $contentHtml . '</main>' . "\n"
            . '<footer class="doc-footer">Generated by <a href="https://github.com/k-kinzal/php-ai-toolkit">php-ai-toolkit</a> docgen</footer>' . "\n"
            . '</div></div>' . "\n"
            . sprintf('<script src="%sassets/search-index.js" defer></script>', $escaper->e($prefix)) . "\n"
            . sprintf('<script src="%sassets/app.js" defer></script>', $escaper->e($prefix)) . "\n"
            . '</body>' . "\n"
            . '</html>' . "\n";
    }

    /**
     * Renders the note shown when a page holds none of the changes.
     *
     * The note is hidden until the script finds that showing the changes
     * alone would leave the page empty, which is an answer rather than a
     * blank page: this page is not part of the comparison.
     */
    public function emptyHint(RenderKit $services): string
    {
        if (!$services->diff->isActive()) {
            return '';
        }

        $escaper = $services->escaper;

        return sprintf(
            '<p class="diff-empty" id="diff-empty" data-changes="%s" data-off="%s" hidden></p>',
            $escaper->e(sprintf(
                'Nothing on this page changed between %s and %s.',
                $services->diff->baseLabel(),
                $services->diff->headLabel(),
            )),
            $escaper->e(sprintf(
                'This page documents what %s had and %s no longer has. Switch to Diff to read it.',
                $services->diff->baseLabel(),
                $services->diff->headLabel(),
            )),
        ) . "\n";
    }

    /**
     * Renders the inline script that restores the display preferences.
     *
     * The theme and the diff mode are applied before the document is laid
     * out, so a page never flashes the wrong colors or the whole file when
     * the reader asked for the changes alone.
     */
    public function bootstrap(RenderKit $services): string
    {
        if (!$services->diff->isActive()) {
            return '<script>try{var t=localStorage.getItem("docgen-theme");if(t){document.documentElement.dataset.ddTheme=t}}catch(e){}</script>';
        }

        return '<script>try{var t=localStorage.getItem("docgen-theme");if(t){document.documentElement.dataset.ddTheme=t}'
            . 'document.documentElement.dataset.diffMode=localStorage.getItem("docgen-diff-mode")||"' . self::DEFAULT_DIFF_MODE . '"}catch(e){}</script>';
    }
}
