on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_NO_INTERACTION: '1'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.0'
            test-script: test:unit:legacy
          - php: '8.1'
            test-script: test:unit
          - php: '8.2'
            test-script: test:unit
          - php: '8.3'
            test-script: test:unit
          - php: '8.4'
            test-script: test:unit
          - php: '8.5'
            test-script: test:unit
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none

      - run: cp "composer.lock.php-${{ matrix.php }}" composer.lock

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: locked
          composer-options: --prefer-dist

      - run: composer ${{ matrix.test-script }}

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none

      - run: cp "composer.lock.php-${{ matrix.php }}" composer.lock

      - run: composer validate --strict --no-check-publish

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: locked
          composer-options: --prefer-dist

      - run: composer format:check

      - run: composer phpstan

      - run: composer compat

      - run: composer loc-guard

      - run: composer deptrac
